Add lab6/thread
ki55el/OOPnD-23-24 pull request #8
Opened 2024-03-27 11:20 UTC by ki55el

2024-03-27 11:36 UTC, ki55el commented
![image](https://github.com/ki55el/OOPnD-23-24/assets/125348732/ecf59d4e-59c2-4383-9af6-c6fbb2dce396)

2024-03-27 12:02 UTC, zaryanezrya requested changes

2024-03-27 12:02 UTC, zaryanezrya commented on SpaceBattle.Lib/SendCommand.cs
> +    public SendCommand(int id, ICommand cmd)
не int id, а сам объект очереди

2024-03-27 12:02 UTC, zaryanezrya commented on SpaceBattle.Lib/CreateAndStartThreadCommand.cs
> +    public CreateAndStartThreadCommand(int id)
Принимается очередь

2024-03-27 12:02 UTC, zaryanezrya commented on SpaceBattle.Lib/CreateAndStartThreadCommand.cs
> +        IoC.Resolve<ConcurrentDictionary<int, BlockingCollection<ICommand>>>("Queue List").TryAdd(_id, queue);
--

2024-03-27 12:02 UTC, zaryanezrya commented on SpaceBattle.Lib/CreateAndStartThreadCommand.cs
> +        IoC.Resolve<ConcurrentDictionary<int, ServerThread>>("ServerThread List").TryAdd(_id, st);
--

2024-03-27 19:48 UTC, ki55el commented
Могут ли быть в этом пулреквесте изменения .yml файла? (это чинит Codecov)

2024-04-06 09:18 UTC, zaryanezrya approved these changes

2024-04-06 09:24 UTC, merged